name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /kasper
domain_name: "http://yourblog-domain.com"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Your Name"

# Disqus config
disqus-shortname: ""
