name: Your New Jekyll Site
description: Blogging about stuffs
meta_description: "Your New Jekyll Site, Blogging about stuffs"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
